export const FILES_LOADED = 'FILES_LOADED';
export const FILES_UPLOADING = 'FILES_UPLOADING';
export const POST_FILES = 'FILES_UPLOADING';
export const FILE_SAVE_SUCCESS = 'FILE_SAVE_SUCCESS';
export const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS';
