export const FILES_LOADED = 'FILES_LOADED';
export const FILES_UPLOADING = 'FILES_UPLOADING';
export const POST_FILES = 'FILES_UPLOADING';
export const FILE_SAVE_SUCCESS = 'FILE_SAVE_SUCCESS';
export const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS';
export const FOLDER_NAME_CHANGED = 'FOLDER_NAME_CHANGED';
export const UPLOAD_COMPLETE = 'UPLOAD_COMPLETE';
export const ARNG_COMPLETE = 'ARNG_COMPLETE';
